import type { LucideIcon } from "lucide-react";
import {
  BookOpen,
  Briefcase,
  CheckSquare,
  Compass,
  Heart,
  HeartHandshake,
  Home,
  LayoutGrid,
  Link2,
  Palette,
  Plane,
  Repeat,
  Settings,
  Sparkles,
  Target,
  Users,
  Wallet,
} from "lucide-react";
import type { NavIconKey } from "@/lib/generation";

export const NAV_ICON_MAP: Record<NavIconKey, LucideIcon> = {
  home: Home,
  goals: Target,
  tasks: CheckSquare,
  ai: Sparkles,
  learning: BookOpen,
  career: Briefcase,
  money: Wallet,
  health: Heart,
  habits: Repeat,
  social: Users,
  discover: Compass,
  relationships: HeartHandshake,
  family: Users,
  travel: Plane,
  hobbies: Palette,
  connect: Link2,
  memory: LayoutGrid,
  more: Settings,
  feed: Compass,
  business: Briefcase,
  home_life: Home,
};
