import type { VitaluEquipment } from "@forward/shared";

/**
 * Licensed movement catalog cached in MotiveLife.
 * Assembler reads this list — we do not call a public exercise API at runtime.
 * “Skip if this bothers X” is wellness language, not a diagnosis.
 */
export type VitaluExercisePattern =
  | "SQUAT"
  | "HINGE"
  | "PUSH"
  | "PULL"
  | "LUNGE"
  | "CORE"
  | "WALK"
  | "MOBILITY";

export type VitaluCatalogExercise = {
  id: string;
  name: string;
  pattern: VitaluExercisePattern;
  equipment: VitaluEquipment[];
  difficulty: 1 | 2 | 3;
  instructions: string;
  skipIf: string[];
  prescription: (level: 1 | 2 | 3) => string;
};

export const VITALU_EXERCISES: VitaluCatalogExercise[] = [
  {
    id: "bodyweight-squat",
    name: "Squat",
    pattern: "SQUAT",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["knees"],
    instructions: "Feet about shoulder-width. Sit back, keep heels down, stand tall.",
    prescription: (l) => (l === 1 ? "3 × 10" : l === 2 ? "3 × 12" : "3 × 15"),
  },
  {
    id: "incline-pushup",
    name: "Incline push-up",
    pattern: "PUSH",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["wrists", "shoulders"],
    instructions: "Hands on a counter or bench. Lower chest, press away. Keep a straight line.",
    prescription: (l) => (l === 1 ? "3 × 8" : l === 2 ? "3 × 10" : "3 × 12"),
  },
  {
    id: "pushup",
    name: "Push-up",
    pattern: "PUSH",
    equipment: ["NONE", "MAT"],
    difficulty: 2,
    skipIf: ["wrists", "shoulders"],
    instructions: "Hands under shoulders. Lower with control, press up. Knees are an allowed regression.",
    prescription: (l) => (l === 1 ? "3 × 6" : l === 2 ? "3 × 8" : "3 × 10"),
  },
  {
    id: "reverse-lunge",
    name: "Reverse lunge",
    pattern: "LUNGE",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["knees"],
    instructions: "Step back, both knees toward 90°, front heel down, stand.",
    prescription: (l) => (l === 1 ? "3 × 8/side" : l === 2 ? "3 × 10/side" : "3 × 12/side"),
  },
  {
    id: "glute-bridge",
    name: "Glute bridge",
    pattern: "HINGE",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["low back"],
    instructions: "Lie on your back, feet planted. Squeeze glutes and lift hips, lower slowly.",
    prescription: (l) => (l === 1 ? "3 × 12" : l === 2 ? "3 × 15" : "3 × 18"),
  },
  {
    id: "plank",
    name: "Plank",
    pattern: "CORE",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["wrists", "low back"],
    instructions: "Elbows under shoulders, body in a line. Breathe. Drop to knees if form fades.",
    prescription: (l) => (l === 1 ? "3 × 20 sec" : l === 2 ? "3 × 30 sec" : "3 × 40 sec"),
  },
  {
    id: "dead-bug",
    name: "Dead bug",
    pattern: "CORE",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["low back"],
    instructions: "On your back, opposite arm and leg reach away. Keep low back gently pressed down.",
    prescription: (l) => (l === 1 ? "3 × 6/side" : "3 × 8/side"),
  },
  {
    id: "row-band",
    name: "Band row",
    pattern: "PULL",
    equipment: ["BANDS"],
    difficulty: 2,
    skipIf: ["shoulders"],
    instructions: "Anchor the band, pull elbows back, squeeze shoulder blades, control the return.",
    prescription: (l) => (l === 2 ? "3 × 12" : "3 × 15"),
  },
  {
    id: "goblet-squat",
    name: "Goblet squat",
    pattern: "SQUAT",
    equipment: ["DUMBBELLS", "GYM"],
    difficulty: 2,
    skipIf: ["knees"],
    instructions: "Hold a dumbbell at your chest. Sit between your heels, stand tall.",
    prescription: (l) => (l === 2 ? "3 × 10" : "3 × 12"),
  },
  {
    id: "db-press",
    name: "Dumbbell floor press",
    pattern: "PUSH",
    equipment: ["DUMBBELLS", "GYM"],
    difficulty: 2,
    skipIf: ["shoulders"],
    instructions: "Lie on the floor, press dumbbells up, lower until elbows kiss the floor.",
    prescription: (l) => "3 × 10",
  },
  {
    id: "rdl",
    name: "Dumbbell RDL",
    pattern: "HINGE",
    equipment: ["DUMBBELLS", "GYM"],
    difficulty: 2,
    skipIf: ["low back", "hamstrings"],
    instructions: "Soft knees, hips back, dumbbells slide down thighs, stand by squeezing glutes.",
    prescription: (l) => "3 × 10",
  },
  {
    id: "walk",
    name: "Brisk walk",
    pattern: "WALK",
    equipment: ["NONE", "MAT", "DUMBBELLS", "BANDS", "GYM"],
    difficulty: 1,
    skipIf: [],
    instructions: "Easy nasal breathing if you can. Swing arms. This is still training.",
    prescription: (l) => (l === 1 ? "10–20 min" : "20 min"),
  },
  {
    id: "cat-cow",
    name: "Cat-cow",
    pattern: "MOBILITY",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["neck"],
    instructions: "On all fours, round and arch slowly with your breath.",
    prescription: () => "1 × 8 slow breaths",
  },
  {
    id: "world-greatest",
    name: "World’s greatest stretch",
    pattern: "MOBILITY",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["knees", "hips"],
    instructions: "Lunge, hand inside the front foot, rotate the chest open, switch sides.",
    prescription: () => "4 / side",
  },
  {
    id: "down-dog",
    name: "Downward dog",
    pattern: "MOBILITY",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["wrists", "shoulders"],
    instructions: "Hands and feet planted, hips high. Pedal the heels. Soft knees are fine.",
    prescription: () => "3 × 20 sec",
  },
  {
    id: "yoga-flow",
    name: "Beginner sun-salute flow",
    pattern: "MOBILITY",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["wrists"],
    instructions: "Mountain → fold → plank → knees-chest-chin or knees down → cobra → down-dog → stand.",
    prescription: () => "4 slow rounds",
  },
  {
    id: "split-squat",
    name: "Split squat",
    pattern: "LUNGE",
    equipment: ["NONE", "MAT", "DUMBBELLS"],
    difficulty: 2,
    skipIf: ["knees"],
    instructions: "Stagger stance, drop the back knee, front heel stays down, stand.",
    prescription: (l) => (l === 1 ? "3 × 6/side" : "3 × 8/side"),
  },
  {
    id: "step-up",
    name: "Step-up",
    pattern: "LUNGE",
    equipment: ["NONE", "GYM"],
    difficulty: 1,
    skipIf: ["knees"],
    instructions: "Step onto a stable stair or box. Drive through the front foot, control the down.",
    prescription: (l) => (l === 1 ? "3 × 8/side" : "3 × 10/side"),
  },
  {
    id: "hip-hinge",
    name: "Bodyweight hip hinge",
    pattern: "HINGE",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["low back"],
    instructions: "Soft knees, hips back, chest proud, stand by squeezing glutes.",
    prescription: (l) => (l === 1 ? "3 × 10" : "3 × 12"),
  },
  {
    id: "good-morning",
    name: "Band good morning",
    pattern: "HINGE",
    equipment: ["BANDS"],
    difficulty: 2,
    skipIf: ["low back"],
    instructions: "Band across shoulders, hinge at the hips, stand tall without yanking the neck.",
    prescription: () => "3 × 10",
  },
  {
    id: "knee-pushup",
    name: "Knee push-up",
    pattern: "PUSH",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["wrists"],
    instructions: "Knees down, body in a line from knees to shoulders. Lower and press.",
    prescription: (l) => (l === 1 ? "3 × 8" : "3 × 12"),
  },
  {
    id: "pike-pushup",
    name: "Pike push-up",
    pattern: "PUSH",
    equipment: ["NONE", "MAT"],
    difficulty: 3,
    skipIf: ["shoulders", "wrists"],
    instructions: "Hips high, lower the head toward the floor, press up. Short range is fine.",
    prescription: () => "3 × 6",
  },
  {
    id: "db-row",
    name: "Dumbbell row",
    pattern: "PULL",
    equipment: ["DUMBBELLS", "GYM"],
    difficulty: 2,
    skipIf: ["low back"],
    instructions: "Hinge, pull the dumbbell to the hip, pause, lower with control.",
    prescription: () => "3 × 10/side",
  },
  {
    id: "superman",
    name: "Superman hold",
    pattern: "PULL",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["low back", "neck"],
    instructions: "Lie face down, lift chest and legs slightly, squeeze, lower. Keep the neck long.",
    prescription: (l) => (l === 1 ? "3 × 20 sec" : "3 × 30 sec"),
  },
  {
    id: "band-pulldown",
    name: "Band pulldown",
    pattern: "PULL",
    equipment: ["BANDS"],
    difficulty: 1,
    skipIf: ["shoulders"],
    instructions: "Anchor high, pull elbows to ribs, control the return.",
    prescription: () => "3 × 12",
  },
  {
    id: "lat-pulldown",
    name: "Lat pulldown",
    pattern: "PULL",
    equipment: ["GYM"],
    difficulty: 2,
    skipIf: ["shoulders"],
    instructions: "Sit tall, pull the bar to the upper chest, don’t yank the neck.",
    prescription: () => "3 × 10",
  },
  {
    id: "leg-press",
    name: "Leg press",
    pattern: "SQUAT",
    equipment: ["GYM"],
    difficulty: 2,
    skipIf: ["knees"],
    instructions: "Feet mid-platform, don’t lock out hard, keep heels down.",
    prescription: () => "3 × 10",
  },
  {
    id: "cable-row",
    name: "Seated cable row",
    pattern: "PULL",
    equipment: ["GYM"],
    difficulty: 2,
    skipIf: ["low back"],
    instructions: "Tall chest, pull to the ribs, pause, return without rounding.",
    prescription: () => "3 × 10",
  },
  {
    id: "chest-press-machine",
    name: "Chest press machine",
    pattern: "PUSH",
    equipment: ["GYM"],
    difficulty: 2,
    skipIf: ["shoulders"],
    instructions: "Handles at mid-chest. Press, don’t bounce. Soft elbows at the top.",
    prescription: () => "3 × 10",
  },
  {
    id: "farmer-carry",
    name: "Farmer carry",
    pattern: "CORE",
    equipment: ["DUMBBELLS", "GYM"],
    difficulty: 2,
    skipIf: ["grips", "shoulders"],
    instructions: "Stand tall with weights at your sides. Walk slow. Ribs down.",
    prescription: (l) => (l === 1 ? "3 × 20 m" : "3 × 30 m"),
  },
  {
    id: "side-plank",
    name: "Side plank",
    pattern: "CORE",
    equipment: ["NONE", "MAT"],
    difficulty: 2,
    skipIf: ["shoulders", "wrists"],
    instructions: "Elbow under shoulder, hips stacked. Drop to a knee if form fades.",
    prescription: (l) => (l === 1 ? "3 × 15 sec/side" : "3 × 25 sec/side"),
  },
  {
    id: "bird-dog",
    name: "Bird dog",
    pattern: "CORE",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["wrists"],
    instructions: "On all fours, opposite arm and leg reach long. Don’t dump the low back.",
    prescription: () => "3 × 6/side",
  },
  {
    id: "hollow-hold",
    name: "Hollow hold",
    pattern: "CORE",
    equipment: ["NONE", "MAT"],
    difficulty: 3,
    skipIf: ["low back", "neck"],
    instructions: "Low back pressed down, arms and legs hover. Bend knees if you need to.",
    prescription: () => "3 × 20 sec",
  },
  {
    id: "wall-sit",
    name: "Wall sit",
    pattern: "SQUAT",
    equipment: ["NONE"],
    difficulty: 1,
    skipIf: ["knees"],
    instructions: "Back on the wall, thighs toward parallel. Breathe. Come up if knees complain.",
    prescription: (l) => (l === 1 ? "3 × 20 sec" : "3 × 30 sec"),
  },
  {
    id: "glute-kickback",
    name: "Glute kickback",
    pattern: "HINGE",
    equipment: ["NONE", "MAT", "BANDS"],
    difficulty: 1,
    skipIf: ["knees"],
    instructions: "On all fours, extend one leg back without arching the back.",
    prescription: () => "3 × 12/side",
  },
  {
    id: "band-pull-apart",
    name: "Band pull-apart",
    pattern: "PULL",
    equipment: ["BANDS"],
    difficulty: 1,
    skipIf: ["shoulders"],
    instructions: "Arms long, pull the band to the chest, squeeze shoulder blades, return slow.",
    prescription: () => "3 × 15",
  },
  {
    id: "shoulder-ca",
    name: "Shoulder CARs",
    pattern: "MOBILITY",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["shoulders"],
    instructions: "Slow biggest comfortable circles. Skip any range that pinches.",
    prescription: () => "5 slow circles / side",
  },
  {
    id: "hip-opener",
    name: "90/90 hip sit",
    pattern: "MOBILITY",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["hips", "knees"],
    instructions: "Both knees at 90°. Sit tall. Switch sides slowly.",
    prescription: () => "4 / side, unhurried",
  },
  {
    id: "child-pose",
    name: "Child’s pose",
    pattern: "MOBILITY",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: ["knees"],
    instructions: "Hips toward heels, arms reach forward. Breathe into the back.",
    prescription: () => "3 × 20 sec",
  },
  {
    id: "march-in-place",
    name: "March in place",
    pattern: "WALK",
    equipment: ["NONE", "MAT"],
    difficulty: 1,
    skipIf: [],
    instructions: "Easy march, swing the arms. Indoor option when a walk isn’t practical.",
    prescription: (l) => (l === 1 ? "8 min" : "12 min"),
  },
];

export function listVitaluExercises(): VitaluCatalogExercise[] {
  return VITALU_EXERCISES;
}
