export type CatalogFood = {
  id: string;
  name: string;
  aliases: string[];
  servingG: number;
  servingLabel: string;
  per100: { kcal: number; protein: number; carbs: number; fat: number; fiber: number };
  waterMl?: number;
  region?: "global" | "americas" | "europe" | "asia" | "africa" | "middle_east" | "oceania";
  source?: "cnf_cache" | "global_cache";
};

/**
 * Global cuisine + drink cache (typical as-eaten estimates).
 * Cached in MotiveLife — never live-searched per keystroke.
 */
export const VITALU_GLOBAL_FOODS: CatalogFood[] = [
  // ── Americas (US / Canada beyond staples) ────────────────────────────────
  { id: "pancakes", name: "Pancakes, buttermilk", aliases: ["pancake", "hotcakes"], servingG: 110, servingLabel: "2 medium", per100: { kcal: 227, protein: 6, carbs: 28, fat: 10, fiber: 1 }, region: "americas", source: "global_cache" },
  { id: "waffle", name: "Waffle", aliases: ["waffles"], servingG: 75, servingLabel: "1 square", per100: { kcal: 291, protein: 8, carbs: 33, fat: 14, fiber: 1.7 }, region: "americas", source: "global_cache" },
  { id: "bacon", name: "Bacon, cooked", aliases: ["strip of bacon"], servingG: 16, servingLabel: "2 strips", per100: { kcal: 541, protein: 37, carbs: 1.4, fat: 42, fiber: 0 }, region: "americas", source: "global_cache" },
  { id: "mac-cheese", name: "Macaroni and cheese", aliases: ["mac and cheese", "mac n cheese"], servingG: 200, servingLabel: "1 cup", per100: { kcal: 164, protein: 7, carbs: 19, fat: 7, fiber: 1 }, region: "americas", source: "global_cache" },
  { id: "fried-chicken", name: "Fried chicken, thigh", aliases: ["kfc", "fried chicken"], servingG: 120, servingLabel: "1 piece", per100: { kcal: 274, protein: 22, carbs: 8, fat: 17, fiber: 0.3 }, region: "americas", source: "global_cache" },
  { id: "hot-dog", name: "Hot dog in bun", aliases: ["hotdog", "frankfurter"], servingG: 110, servingLabel: "1", per100: { kcal: 247, protein: 10, carbs: 18, fat: 15, fiber: 0.7 }, region: "americas", source: "global_cache" },
  { id: "cheeseburger", name: "Cheeseburger", aliases: ["cheese burger"], servingG: 160, servingLabel: "1 sandwich", per100: { kcal: 263, protein: 15, carbs: 22, fat: 13, fiber: 1.2 }, region: "americas", source: "global_cache" },
  { id: "taco", name: "Beef taco", aliases: ["tacos", "hard shell taco"], servingG: 100, servingLabel: "1 taco", per100: { kcal: 216, protein: 9, carbs: 16, fat: 13, fiber: 2.2 }, region: "americas", source: "global_cache" },
  { id: "quesadilla", name: "Cheese quesadilla", aliases: [], servingG: 180, servingLabel: "1", per100: { kcal: 274, protein: 12, carbs: 24, fat: 14, fiber: 1.5 }, region: "americas", source: "global_cache" },
  { id: "nachos", name: "Nachos with cheese", aliases: ["nacho"], servingG: 180, servingLabel: "1 plate", per100: { kcal: 306, protein: 8, carbs: 32, fat: 17, fiber: 2.5 }, region: "americas", source: "global_cache" },
  { id: "chicken-wings", name: "Chicken wings, baked", aliases: ["wings", "buffalo wings"], servingG: 140, servingLabel: "4 pieces", per100: { kcal: 203, protein: 18, carbs: 0, fat: 14, fiber: 0 }, region: "americas", source: "global_cache" },
  { id: "mashed-potato", name: "Mashed potatoes", aliases: ["mash"], servingG: 210, servingLabel: "1 cup", per100: { kcal: 106, protein: 2, carbs: 17, fat: 4, fiber: 1.5 }, region: "americas", source: "global_cache" },
  { id: "cornbread", name: "Cornbread", aliases: ["corn bread"], servingG: 65, servingLabel: "1 square", per100: { kcal: 330, protein: 7, carbs: 43, fat: 14, fiber: 2 }, region: "americas", source: "global_cache" },
  { id: "pbj", name: "Peanut butter and jelly sandwich", aliases: ["pb&j", "pbj"], servingG: 100, servingLabel: "1 sandwich", per100: { kcal: 340, protein: 11, carbs: 41, fat: 15, fiber: 3 }, region: "americas", source: "global_cache" },
  { id: "donut", name: "Donut, glazed", aliases: ["doughnut"], servingG: 45, servingLabel: "1", per100: { kcal: 421, protein: 5, carbs: 51, fat: 23, fiber: 1.2 }, region: "americas", source: "global_cache" },
  { id: "brownie", name: "Brownie", aliases: [], servingG: 56, servingLabel: "1 square", per100: { kcal: 405, protein: 5, carbs: 55, fat: 20, fiber: 2.1 }, region: "americas", source: "global_cache" },
  { id: "apple-pie", name: "Apple pie", aliases: ["pie"], servingG: 125, servingLabel: "1 slice", per100: { kcal: 237, protein: 2, carbs: 34, fat: 11, fiber: 1.6 }, region: "americas", source: "global_cache" },
  { id: "caesar-salad", name: "Caesar salad with dressing", aliases: ["caesar"], servingG: 200, servingLabel: "1 bowl", per100: { kcal: 160, protein: 6, carbs: 7, fat: 13, fiber: 1.8 }, region: "americas", source: "global_cache" },
  { id: "clam-chowder", name: "New England clam chowder", aliases: ["chowder"], servingG: 248, servingLabel: "1 cup", per100: { kcal: 79, protein: 4, carbs: 8, fat: 3.5, fiber: 0.6 }, region: "americas", source: "global_cache" },
  { id: "bbq-ribs", name: "BBQ pork ribs", aliases: ["ribs", "barbecue"], servingG: 140, servingLabel: "3 ribs", per100: { kcal: 292, protein: 22, carbs: 8, fat: 19, fiber: 0.2 }, region: "americas", source: "global_cache" },
  { id: "corn-cob", name: "Corn on the cob", aliases: ["corn", "sweetcorn"], servingG: 90, servingLabel: "1 ear", per100: { kcal: 96, protein: 3.4, carbs: 21, fat: 1.5, fiber: 2.4 }, region: "americas", source: "global_cache" },
  { id: "colestaw", name: "Coleslaw", aliases: ["slaw"], servingG: 90, servingLabel: "½ cup", per100: { kcal: 153, protein: 1, carbs: 11, fat: 12, fiber: 1.8 }, region: "americas", source: "global_cache" },
  { id: "latte", name: "Caffè latte", aliases: ["latte", "cafe latte"], servingG: 240, servingLabel: "1 cup", per100: { kcal: 43, protein: 2.9, carbs: 4.3, fat: 1.8, fiber: 0 }, region: "americas", source: "global_cache" },
  { id: "iced-coffee", name: "Iced coffee, sweetened", aliases: ["cold brew"], servingG: 350, servingLabel: "1 tall", per100: { kcal: 18, protein: 0.2, carbs: 4, fat: 0.1, fiber: 0 }, region: "americas", source: "global_cache" },
  { id: "lemonade", name: "Lemonade", aliases: [], servingG: 300, servingLabel: "1 glass", per100: { kcal: 40, protein: 0.1, carbs: 10.5, fat: 0, fiber: 0 }, region: "americas", source: "global_cache" },
  { id: "iced-tea", name: "Iced tea, sweetened", aliases: ["sweet tea"], servingG: 300, servingLabel: "1 glass", per100: { kcal: 27, protein: 0, carbs: 7, fat: 0, fiber: 0 }, region: "americas", source: "global_cache" },
  { id: "sports-drink", name: "Sports drink", aliases: ["gatorade", "electrolyte drink"], servingG: 355, servingLabel: "1 bottle", per100: { kcal: 26, protein: 0, carbs: 6.4, fat: 0, fiber: 0 }, region: "americas", source: "global_cache" },
  { id: "milkshake", name: "Chocolate milkshake", aliases: ["shake"], servingG: 300, servingLabel: "1 medium", per100: { kcal: 135, protein: 3.5, carbs: 22, fat: 4, fiber: 0.5 }, region: "americas", source: "global_cache" },
  { id: "diet-cola", name: "Diet cola", aliases: ["diet soda", "diet pop", "coke zero"], servingG: 355, servingLabel: "1 can", per100: { kcal: 0, protein: 0, carbs: 0, fat: 0, fiber: 0 }, region: "americas", source: "global_cache" },
  { id: "sparkling-water", name: "Sparkling water", aliases: ["soda water", "seltzer", "la croix"], servingG: 355, servingLabel: "1 can", per100: { kcal: 0, protein: 0, carbs: 0, fat: 0, fiber: 0 }, region: "americas", source: "global_cache" },
  { id: "smoothie-fruit", name: "Fruit smoothie", aliases: ["smoothie"], servingG: 300, servingLabel: "1 cup", per100: { kcal: 68, protein: 1.2, carbs: 15, fat: 0.5, fiber: 1.4 }, region: "americas", source: "global_cache" },
  { id: "oat-milk", name: "Oat milk", aliases: ["oatmilk"], servingG: 240, servingLabel: "1 cup", per100: { kcal: 48, protein: 1.2, carbs: 7, fat: 2, fiber: 0.8 }, region: "americas", source: "global_cache" },
  { id: "almond-milk", name: "Almond milk, unsweetened", aliases: ["almondmilk"], servingG: 240, servingLabel: "1 cup", per100: { kcal: 15, protein: 0.6, carbs: 0.6, fat: 1.1, fiber: 0.2 }, region: "americas", source: "global_cache" },
  { id: "kombucha", name: "Kombucha", aliases: [], servingG: 240, servingLabel: "1 bottle", per100: { kcal: 13, protein: 0.2, carbs: 3, fat: 0, fiber: 0 }, region: "americas", source: "global_cache" },

  // ── Latin America & Caribbean ────────────────────────────────────────────
  { id: "arepa", name: "Arepa, cheese", aliases: [], servingG: 130, servingLabel: "1", per100: { kcal: 218, protein: 8, carbs: 28, fat: 8, fiber: 2.4 }, region: "americas", source: "global_cache" },
  { id: "empanada", name: "Beef empanada", aliases: ["empanadas"], servingG: 90, servingLabel: "1", per100: { kcal: 289, protein: 10, carbs: 27, fat: 15, fiber: 1.5 }, region: "americas", source: "global_cache" },
  { id: "ceviche", name: "Fish ceviche", aliases: [], servingG: 180, servingLabel: "1 bowl", per100: { kcal: 97, protein: 14, carbs: 6, fat: 2, fiber: 1 }, region: "americas", source: "global_cache" },
  { id: "feijoada", name: "Feijoada", aliases: [], servingG: 300, servingLabel: "1 bowl", per100: { kcal: 145, protein: 10, carbs: 12, fat: 6, fiber: 4 }, region: "americas", source: "global_cache" },
  { id: "acai-bowl", name: "Açaí bowl", aliases: ["acai", "açaí"], servingG: 280, servingLabel: "1 bowl", per100: { kcal: 125, protein: 2.5, carbs: 22, fat: 4, fiber: 3.5 }, region: "americas", source: "global_cache" },
  { id: "arroz-pollo", name: "Arroz con pollo", aliases: ["arroz con pollo"], servingG: 300, servingLabel: "1 plate", per100: { kcal: 142, protein: 10, carbs: 16, fat: 4, fiber: 1.2 }, region: "americas", source: "global_cache" },
  { id: "pupusa", name: "Pupusa, cheese", aliases: ["pupusas"], servingG: 110, servingLabel: "1", per100: { kcal: 232, protein: 8, carbs: 30, fat: 9, fiber: 2.8 }, region: "americas", source: "global_cache" },
  { id: "tostones", name: "Tostones", aliases: ["fried plantain"], servingG: 80, servingLabel: "4 pieces", per100: { kcal: 196, protein: 1.2, carbs: 29, fat: 9, fiber: 2.1 }, region: "americas", source: "global_cache" },
  { id: "jerk-chicken", name: "Jerk chicken", aliases: ["jerk"], servingG: 150, servingLabel: "1 serving", per100: { kcal: 185, protein: 24, carbs: 3, fat: 8, fiber: 0.5 }, region: "americas", source: "global_cache" },
  { id: "rice-peas", name: "Rice and peas", aliases: ["rice and beans caribbean"], servingG: 200, servingLabel: "1 cup", per100: { kcal: 148, protein: 4.5, carbs: 26, fat: 3, fiber: 2.5 }, region: "americas", source: "global_cache" },
  { id: "pao-queijo", name: "Pão de queijo", aliases: ["pao de queijo", "cheese bread"], servingG: 40, servingLabel: "2 pieces", per100: { kcal: 320, protein: 8, carbs: 36, fat: 16, fiber: 0.8 }, region: "americas", source: "global_cache" },
  { id: "horchata", name: "Horchata", aliases: [], servingG: 240, servingLabel: "1 glass", per100: { kcal: 67, protein: 1, carbs: 13, fat: 1.2, fiber: 0.2 }, region: "americas", source: "global_cache" },
  { id: "mate", name: "Yerba mate", aliases: ["maté", "chimarrão"], servingG: 200, servingLabel: "1 gourd", per100: { kcal: 4, protein: 0.3, carbs: 0.7, fat: 0, fiber: 0 }, region: "americas", source: "global_cache" },
  { id: "mojito", name: "Mojito", aliases: [], servingG: 200, servingLabel: "1 glass", per100: { kcal: 74, protein: 0.1, carbs: 7, fat: 0, fiber: 0.2 }, region: "americas", source: "global_cache" },

  // ── Europe ───────────────────────────────────────────────────────────────
  { id: "croissant", name: "Croissant, butter", aliases: [], servingG: 57, servingLabel: "1", per100: { kcal: 406, protein: 8, carbs: 46, fat: 21, fiber: 2.6 }, region: "europe", source: "global_cache" },
  { id: "baguette", name: "Baguette", aliases: ["french bread"], servingG: 50, servingLabel: "1 slice", per100: { kcal: 274, protein: 9, carbs: 56, fat: 1.5, fiber: 2.4 }, region: "europe", source: "global_cache" },
  { id: "brie", name: "Brie", aliases: [], servingG: 30, servingLabel: "30 g", per100: { kcal: 334, protein: 21, carbs: 0.5, fat: 28, fiber: 0 }, region: "europe", source: "global_cache" },
  { id: "parmesan", name: "Parmesan", aliases: ["parmigiano"], servingG: 20, servingLabel: "20 g", per100: { kcal: 392, protein: 36, carbs: 3.2, fat: 26, fiber: 0 }, region: "europe", source: "global_cache" },
  { id: "risotto", name: "Mushroom risotto", aliases: [], servingG: 250, servingLabel: "1 bowl", per100: { kcal: 142, protein: 4, carbs: 20, fat: 5, fiber: 1 }, region: "europe", source: "global_cache" },
  { id: "paella", name: "Seafood paella", aliases: [], servingG: 300, servingLabel: "1 plate", per100: { kcal: 138, protein: 9, carbs: 16, fat: 4, fiber: 1.1 }, region: "europe", source: "global_cache" },
  { id: "lasagna", name: "Lasagna, meat", aliases: ["lasagne"], servingG: 250, servingLabel: "1 square", per100: { kcal: 135, protein: 8, carbs: 11, fat: 6, fiber: 1.2 }, region: "europe", source: "global_cache" },
  { id: "carbonara", name: "Spaghetti carbonara", aliases: ["carbonara"], servingG: 280, servingLabel: "1 plate", per100: { kcal: 174, protein: 8, carbs: 18, fat: 8, fiber: 1 }, region: "europe", source: "global_cache" },
  { id: "pesto-pasta", name: "Pesto pasta", aliases: ["pesto"], servingG: 250, servingLabel: "1 plate", per100: { kcal: 168, protein: 5, carbs: 20, fat: 8, fiber: 1.4 }, region: "europe", source: "global_cache" },
  { id: "minestrone", name: "Minestrone", aliases: [], servingG: 250, servingLabel: "1 bowl", per100: { kcal: 52, protein: 2.2, carbs: 8, fat: 1.2, fiber: 2 }, region: "europe", source: "global_cache" },
  { id: "fish-chips", name: "Fish and chips", aliases: ["fish n chips"], servingG: 300, servingLabel: "1 serving", per100: { kcal: 195, protein: 10, carbs: 18, fat: 9, fiber: 1.5 }, region: "europe", source: "global_cache" },
  { id: "shepherd-pie", name: "Shepherd’s pie", aliases: ["cottage pie"], servingG: 280, servingLabel: "1 serving", per100: { kcal: 128, protein: 8, carbs: 12, fat: 5, fiber: 1.4 }, region: "europe", source: "global_cache" },
  { id: "schnitzel", name: "Wiener schnitzel", aliases: ["schnitzel"], servingG: 180, servingLabel: "1 cutlet", per100: { kcal: 228, protein: 16, carbs: 12, fat: 13, fiber: 0.6 }, region: "europe", source: "global_cache" },
  { id: "pierogi", name: "Pierogi, potato", aliases: ["perogies", "pierogies"], servingG: 180, servingLabel: "6 pieces", per100: { kcal: 186, protein: 6, carbs: 28, fat: 5, fiber: 1.6 }, region: "europe", source: "global_cache" },
  { id: "goulash", name: "Beef goulash", aliases: ["gulasch"], servingG: 280, servingLabel: "1 bowl", per100: { kcal: 112, protein: 10, carbs: 6, fat: 5, fiber: 1.2 }, region: "europe", source: "global_cache" },
  { id: "moussaka", name: "Moussaka", aliases: [], servingG: 250, servingLabel: "1 square", per100: { kcal: 138, protein: 8, carbs: 8, fat: 8, fiber: 1.8 }, region: "europe", source: "global_cache" },
  { id: "gyro", name: "Chicken gyro", aliases: ["gyros", "doner", "dürüm"], servingG: 250, servingLabel: "1 wrap", per100: { kcal: 196, protein: 13, carbs: 18, fat: 8, fiber: 1.5 }, region: "europe", source: "global_cache" },
  { id: "quiche", name: "Quiche Lorraine", aliases: ["quiche"], servingG: 140, servingLabel: "1 slice", per100: { kcal: 262, protein: 10, carbs: 14, fat: 19, fiber: 0.7 }, region: "europe", source: "global_cache" },
  { id: "crepe", name: "Crêpe, plain", aliases: ["crepe", "crêpes"], servingG: 80, servingLabel: "2", per100: { kcal: 188, protein: 6, carbs: 26, fat: 6, fiber: 0.8 }, region: "europe", source: "global_cache" },
  { id: "ratatouille", name: "Ratatouille", aliases: [], servingG: 200, servingLabel: "1 cup", per100: { kcal: 58, protein: 1.5, carbs: 8, fat: 2.5, fiber: 2.4 }, region: "europe", source: "global_cache" },
  { id: "gazpacho", name: "Gazpacho", aliases: [], servingG: 250, servingLabel: "1 bowl", per100: { kcal: 36, protein: 0.8, carbs: 5, fat: 1.5, fiber: 1.2 }, region: "europe", source: "global_cache" },
  { id: "tiramisu", name: "Tiramisu", aliases: [], servingG: 100, servingLabel: "1 slice", per100: { kcal: 283, protein: 5, carbs: 28, fat: 16, fiber: 0.8 }, region: "europe", source: "global_cache" },
  { id: "gelato", name: "Gelato, pistachio", aliases: ["gelato"], servingG: 80, servingLabel: "2 scoops", per100: { kcal: 208, protein: 4.5, carbs: 24, fat: 10, fiber: 0.6 }, region: "europe", source: "global_cache" },
  { id: "pretzel", name: "Soft pretzel", aliases: ["pretzel"], servingG: 115, servingLabel: "1", per100: { kcal: 338, protein: 8, carbs: 69, fat: 3, fiber: 2.4 }, region: "europe", source: "global_cache" },
  { id: "kielbasa", name: "Kielbasa, grilled", aliases: ["kielbasa", "polish sausage"], servingG: 85, servingLabel: "1 link", per100: { kcal: 309, protein: 13, carbs: 4, fat: 27, fiber: 0 }, region: "europe", source: "global_cache" },
  { id: "baklava", name: "Baklava", aliases: [], servingG: 50, servingLabel: "1 piece", per100: { kcal: 428, protein: 6, carbs: 45, fat: 25, fiber: 2 }, region: "europe", source: "global_cache" },
  { id: "espresso", name: "Espresso", aliases: ["shot"], servingG: 30, servingLabel: "1 shot", per100: { kcal: 9, protein: 0.1, carbs: 1.7, fat: 0.2, fiber: 0 }, region: "europe", source: "global_cache" },
  { id: "cappuccino", name: "Cappuccino", aliases: [], servingG: 180, servingLabel: "1 cup", per100: { kcal: 37, protein: 2, carbs: 3, fat: 2, fiber: 0 }, region: "europe", source: "global_cache" },
  { id: "cider", name: "Apple cider, alcoholic", aliases: ["cider"], servingG: 330, servingLabel: "1 pint", per100: { kcal: 47, protein: 0, carbs: 6, fat: 0, fiber: 0 }, region: "europe", source: "global_cache" },
  { id: "stout", name: "Stout beer", aliases: ["guinness", "stout"], servingG: 440, servingLabel: "1 pint", per100: { kcal: 37, protein: 0.4, carbs: 3, fat: 0, fiber: 0 }, region: "europe", source: "global_cache" },
  { id: "wine-white", name: "Wine, white", aliases: ["white wine"], servingG: 147, servingLabel: "5 oz", per100: { kcal: 82, protein: 0.1, carbs: 2.6, fat: 0, fiber: 0 }, region: "europe", source: "global_cache" },
  { id: "prosecco", name: "Prosecco", aliases: ["champagne", "sparkling wine"], servingG: 150, servingLabel: "1 flute", per100: { kcal: 74, protein: 0.1, carbs: 2, fat: 0, fiber: 0 }, region: "europe", source: "global_cache" },

  // ── Asia (East, SE, South) ───────────────────────────────────────────────
  { id: "ramen", name: "Ramen, tonkotsu-style", aliases: ["ramen bowl"], servingG: 500, servingLabel: "1 bowl", per100: { kcal: 92, protein: 4.5, carbs: 11, fat: 3.2, fiber: 0.8 }, region: "asia", source: "global_cache" },
  { id: "pho", name: "Phở bò", aliases: ["pho", "phở"], servingG: 500, servingLabel: "1 bowl", per100: { kcal: 58, protein: 4, carbs: 7, fat: 1.4, fiber: 0.6 }, region: "asia", source: "global_cache" },
  { id: "pad-thai", name: "Pad Thai", aliases: ["padthai"], servingG: 300, servingLabel: "1 plate", per100: { kcal: 153, protein: 7, carbs: 20, fat: 5, fiber: 1.5 }, region: "asia", source: "global_cache" },
  { id: "fried-rice", name: "Fried rice, chicken", aliases: ["yangzhou fried rice"], servingG: 250, servingLabel: "1 plate", per100: { kcal: 164, protein: 7, carbs: 22, fat: 5.5, fiber: 0.9 }, region: "asia", source: "global_cache" },
  { id: "dumpling", name: "Pork dumplings, steamed", aliases: ["gyoza", "jiaozi", "potsticker"], servingG: 120, servingLabel: "6 pieces", per100: { kcal: 186, protein: 8, carbs: 22, fat: 7, fiber: 1.2 }, region: "asia", source: "global_cache" },
  { id: "bao", name: "Char siu bao", aliases: ["bao bun", "pork bun"], servingG: 90, servingLabel: "1 bun", per100: { kcal: 231, protein: 8, carbs: 36, fat: 6, fiber: 1.4 }, region: "asia", source: "global_cache" },
  { id: "miso-soup", name: "Miso soup", aliases: ["miso"], servingG: 240, servingLabel: "1 bowl", per100: { kcal: 21, protein: 1.6, carbs: 2.5, fat: 0.6, fiber: 0.5 }, region: "asia", source: "global_cache" },
  { id: "bibimbap", name: "Bibimbap", aliases: [], servingG: 400, servingLabel: "1 bowl", per100: { kcal: 118, protein: 6, carbs: 16, fat: 3.5, fiber: 1.8 }, region: "asia", source: "global_cache" },
  { id: "kimchi", name: "Kimchi", aliases: [], servingG: 50, servingLabel: "¼ cup", per100: { kcal: 15, protein: 1.1, carbs: 2.4, fat: 0.5, fiber: 1.6 }, region: "asia", source: "global_cache" },
  { id: "bulgogi", name: "Beef bulgogi", aliases: ["bulgogi"], servingG: 150, servingLabel: "1 serving", per100: { kcal: 168, protein: 18, carbs: 8, fat: 7, fiber: 0.4 }, region: "asia", source: "global_cache" },
  { id: "katsu", name: "Chicken katsu", aliases: ["katsu", "tonkatsu"], servingG: 180, servingLabel: "1 cutlet", per100: { kcal: 242, protein: 16, carbs: 14, fat: 13, fiber: 0.6 }, region: "asia", source: "global_cache" },
  { id: "udon", name: "Udon, kitsune", aliases: ["udon"], servingG: 400, servingLabel: "1 bowl", per100: { kcal: 86, protein: 3, carbs: 16, fat: 1, fiber: 0.8 }, region: "asia", source: "global_cache" },
  { id: "congee", name: "Congee, plain", aliases: ["jook", "rice porridge"], servingG: 300, servingLabel: "1 bowl", per100: { kcal: 47, protein: 1, carbs: 10, fat: 0.3, fiber: 0.2 }, region: "asia", source: "global_cache" },
  { id: "spring-roll", name: "Fresh spring rolls", aliases: ["gỏi cuốn", "summer roll"], servingG: 100, servingLabel: "2 rolls", per100: { kcal: 109, protein: 5, carbs: 16, fat: 2.5, fiber: 1.4 }, region: "asia", source: "global_cache" },
  { id: "satay", name: "Chicken satay", aliases: ["sate"], servingG: 120, servingLabel: "4 skewers", per100: { kcal: 198, protein: 20, carbs: 6, fat: 10, fiber: 0.8 }, region: "asia", source: "global_cache" },
  { id: "nasi-goreng", name: "Nasi goreng", aliases: [], servingG: 300, servingLabel: "1 plate", per100: { kcal: 168, protein: 7, carbs: 22, fat: 6, fiber: 1.2 }, region: "asia", source: "global_cache" },
  { id: "laksa", name: "Laksa", aliases: [], servingG: 450, servingLabel: "1 bowl", per100: { kcal: 112, protein: 6, carbs: 11, fat: 5, fiber: 1 }, region: "asia", source: "global_cache" },
  { id: "wonton-soup", name: "Wonton soup", aliases: ["wonton"], servingG: 350, servingLabel: "1 bowl", per100: { kcal: 54, protein: 3.5, carbs: 5, fat: 2, fiber: 0.4 }, region: "asia", source: "global_cache" },
  { id: "teriyaki-chicken", name: "Teriyaki chicken", aliases: ["teriyaki"], servingG: 180, servingLabel: "1 serving", per100: { kcal: 176, protein: 20, carbs: 10, fat: 6, fiber: 0.2 }, region: "asia", source: "global_cache" },
  { id: "poke-bowl", name: "Poke bowl, tuna", aliases: ["poke"], servingG: 350, servingLabel: "1 bowl", per100: { kcal: 128, protein: 10, carbs: 14, fat: 4, fiber: 1.6 }, region: "asia", source: "global_cache" },
  { id: "naan", name: "Naan", aliases: ["nan bread"], servingG: 90, servingLabel: "1 piece", per100: { kcal: 271, protein: 8, carbs: 46, fat: 6, fiber: 2 }, region: "asia", source: "global_cache" },
  { id: "dal", name: "Dal tadka", aliases: ["daal", "lentil curry"], servingG: 200, servingLabel: "1 cup", per100: { kcal: 108, protein: 6, carbs: 14, fat: 3, fiber: 4.5 }, region: "asia", source: "global_cache" },
  { id: "biryani", name: "Chicken biryani", aliases: ["biryani"], servingG: 300, servingLabel: "1 plate", per100: { kcal: 148, protein: 8, carbs: 18, fat: 5, fiber: 1.2 }, region: "asia", source: "global_cache" },
  { id: "samosa", name: "Vegetable samosa", aliases: ["samosas"], servingG: 60, servingLabel: "1", per100: { kcal: 262, protein: 5, carbs: 32, fat: 13, fiber: 2.8 }, region: "asia", source: "global_cache" },
  { id: "dosa", name: "Masala dosa", aliases: ["dosa"], servingG: 200, servingLabel: "1", per100: { kcal: 168, protein: 4, carbs: 28, fat: 4.5, fiber: 2.2 }, region: "asia", source: "global_cache" },
  { id: "roti", name: "Roti, whole wheat", aliases: ["chapati", "phulka"], servingG: 40, servingLabel: "1", per100: { kcal: 297, protein: 10, carbs: 50, fat: 6, fiber: 7 }, region: "asia", source: "global_cache" },
  { id: "tikka-masala", name: "Chicken tikka masala", aliases: ["tikka masala"], servingG: 250, servingLabel: "1 serving", per100: { kcal: 142, protein: 12, carbs: 8, fat: 7, fiber: 1.4 }, region: "asia", source: "global_cache" },
  { id: "paneer", name: "Palak paneer", aliases: ["paneer", "saag paneer"], servingG: 200, servingLabel: "1 cup", per100: { kcal: 148, protein: 8, carbs: 7, fat: 10, fiber: 2.2 }, region: "asia", source: "global_cache" },
  { id: "mango-lassi", name: "Mango lassi", aliases: ["lassi"], servingG: 250, servingLabel: "1 glass", per100: { kcal: 74, protein: 2.5, carbs: 13, fat: 1.6, fiber: 0.4 }, region: "asia", source: "global_cache" },
  { id: "chai", name: "Masala chai with milk", aliases: ["chai", "chai tea"], servingG: 200, servingLabel: "1 cup", per100: { kcal: 42, protein: 1.6, carbs: 6, fat: 1.4, fiber: 0 }, region: "asia", source: "global_cache" },
  { id: "matcha-latte", name: "Matcha latte", aliases: ["matcha"], servingG: 240, servingLabel: "1 cup", per100: { kcal: 48, protein: 2, carbs: 6, fat: 1.8, fiber: 0.3 }, region: "asia", source: "global_cache" },
  { id: "boba", name: "Bubble tea, milk", aliases: ["boba", "bubble tea", "pearl milk tea"], servingG: 400, servingLabel: "1 cup", per100: { kcal: 72, protein: 1.2, carbs: 14, fat: 1.4, fiber: 0.3 }, region: "asia", source: "global_cache" },
  { id: "coconut-water", name: "Coconut water", aliases: [], servingG: 240, servingLabel: "1 cup", per100: { kcal: 19, protein: 0.7, carbs: 3.7, fat: 0.2, fiber: 1.1 }, region: "asia", source: "global_cache" },
  { id: "green-tea", name: "Green tea", aliases: ["sencha"], servingG: 240, servingLabel: "1 cup", per100: { kcal: 1, protein: 0, carbs: 0.2, fat: 0, fiber: 0 }, region: "asia", source: "global_cache" },
  { id: "sake", name: "Sake", aliases: ["nihonshu"], servingG: 180, servingLabel: "1 tokkuri", per100: { kcal: 134, protein: 0.5, carbs: 5, fat: 0, fiber: 0 }, region: "asia", source: "global_cache" },
  { id: "mango", name: "Mango", aliases: [], servingG: 165, servingLabel: "1 cup", per100: { kcal: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6 }, region: "asia", source: "global_cache" },

  // ── Africa ───────────────────────────────────────────────────────────────
  { id: "jollof-rice", name: "Jollof rice", aliases: ["jollof"], servingG: 250, servingLabel: "1 plate", per100: { kcal: 148, protein: 4, carbs: 24, fat: 4, fiber: 1.6 }, region: "africa", source: "global_cache" },
  { id: "injera", name: "Injera", aliases: [], servingG: 100, servingLabel: "1 round piece", per100: { kcal: 131, protein: 4.5, carbs: 25, fat: 1.2, fiber: 3.5 }, region: "africa", source: "global_cache" },
  { id: "doro-wat", name: "Doro wot", aliases: ["doro wat", "doro wet"], servingG: 220, servingLabel: "1 serving", per100: { kcal: 142, protein: 12, carbs: 6, fat: 8, fiber: 1.4 }, region: "africa", source: "global_cache" },
  { id: "fufu", name: "Fufu", aliases: ["foofoo"], servingG: 200, servingLabel: "1 ball", per100: { kcal: 144, protein: 1, carbs: 35, fat: 0.2, fiber: 1.8 }, region: "africa", source: "global_cache" },
  { id: "egusi", name: "Egusi soup", aliases: ["egusi"], servingG: 250, servingLabel: "1 bowl", per100: { kcal: 156, protein: 9, carbs: 6, fat: 11, fiber: 2.2 }, region: "africa", source: "global_cache" },
  { id: "suya", name: "Suya, beef", aliases: ["suya"], servingG: 120, servingLabel: "1 skewer plate", per100: { kcal: 218, protein: 24, carbs: 4, fat: 12, fiber: 1 }, region: "africa", source: "global_cache" },
  { id: "bobotie", name: "Bobotie", aliases: [], servingG: 220, servingLabel: "1 serving", per100: { kcal: 168, protein: 11, carbs: 10, fat: 9, fiber: 1.2 }, region: "africa", source: "global_cache" },
  { id: "bunny-chow", name: "Bunny chow, bean", aliases: ["bunny chow"], servingG: 350, servingLabel: "¼ loaf", per100: { kcal: 162, protein: 6, carbs: 24, fat: 4.5, fiber: 3 }, region: "africa", source: "global_cache" },
  { id: "couscous", name: "Couscous, cooked", aliases: [], servingG: 157, servingLabel: "1 cup", per100: { kcal: 112, protein: 3.8, carbs: 23, fat: 0.2, fiber: 1.4 }, region: "africa", source: "global_cache" },
  { id: "tagine", name: "Chicken tagine", aliases: ["tajine"], servingG: 280, servingLabel: "1 serving", per100: { kcal: 118, protein: 11, carbs: 8, fat: 4.5, fiber: 2 }, region: "africa", source: "global_cache" },
  { id: "shakshuka", name: "Shakshuka", aliases: ["shakshouka"], servingG: 250, servingLabel: "1 skillet serve", per100: { kcal: 92, protein: 6, carbs: 6, fat: 5, fiber: 1.8 }, region: "africa", source: "global_cache" },
  { id: "koshari", name: "Koshari", aliases: ["koshary", "kushari"], servingG: 300, servingLabel: "1 plate", per100: { kcal: 142, protein: 5, carbs: 26, fat: 2.5, fiber: 3.2 }, region: "africa", source: "global_cache" },
  { id: "ugali", name: "Ugali", aliases: ["sadza", "nsima", "pap"], servingG: 200, servingLabel: "1 serving", per100: { kcal: 116, protein: 2.5, carbs: 25, fat: 0.5, fiber: 1.6 }, region: "africa", source: "global_cache" },
  { id: "plantain-fried", name: "Fried plantain", aliases: ["dodo", "kelewele", "plantain"], servingG: 100, servingLabel: "½ cup", per100: { kcal: 224, protein: 1.3, carbs: 31, fat: 12, fiber: 2.3 }, region: "africa", source: "global_cache" },
  { id: "yam-boiled", name: "Boiled yam", aliases: ["yam", "puna yam"], servingG: 150, servingLabel: "1 cup", per100: { kcal: 118, protein: 1.5, carbs: 28, fat: 0.2, fiber: 4 }, region: "africa", source: "global_cache" },
  { id: "okra-stew", name: "Okra stew", aliases: ["okra soup", "ila"], servingG: 240, servingLabel: "1 bowl", per100: { kcal: 78, protein: 4, carbs: 8, fat: 3.5, fiber: 2.8 }, region: "africa", source: "global_cache" },
  { id: "peanut-stew", name: "Groundnut stew", aliases: ["maafe", "peanut stew", "mafé"], servingG: 250, servingLabel: "1 bowl", per100: { kcal: 148, protein: 8, carbs: 10, fat: 8, fiber: 2.4 }, region: "africa", source: "global_cache" },
  { id: "pilau", name: "Beef pilau", aliases: ["pilaf", "pilau rice"], servingG: 250, servingLabel: "1 plate", per100: { kcal: 156, protein: 8, carbs: 20, fat: 5, fiber: 1.2 }, region: "africa", source: "global_cache" },
  { id: "bissap", name: "Bissap (hibiscus tea)", aliases: ["sobolo", "zobo", "karkadeh", "hibiscus tea"], servingG: 250, servingLabel: "1 glass", per100: { kcal: 28, protein: 0.2, carbs: 7, fat: 0, fiber: 0.2 }, region: "africa", source: "global_cache" },
  { id: "rooibos", name: "Rooibos tea", aliases: ["red bush"], servingG: 240, servingLabel: "1 cup", per100: { kcal: 1, protein: 0, carbs: 0.2, fat: 0, fiber: 0 }, region: "africa", source: "global_cache" },

  // ── Middle East ──────────────────────────────────────────────────────────
  { id: "shawarma", name: "Chicken shawarma wrap", aliases: ["shawarma", "schwarma"], servingG: 280, servingLabel: "1 wrap", per100: { kcal: 186, protein: 12, carbs: 18, fat: 7, fiber: 1.6 }, region: "middle_east", source: "global_cache" },
  { id: "kebab", name: "Lamb kebab", aliases: ["kabob", "kofta", "shish kebab"], servingG: 150, servingLabel: "1 skewer plate", per100: { kcal: 215, protein: 20, carbs: 3, fat: 14, fiber: 0.4 }, region: "middle_east", source: "global_cache" },
  { id: "falafel", name: "Falafel pita", aliases: ["falafel"], servingG: 220, servingLabel: "1 pita", per100: { kcal: 198, protein: 8, carbs: 24, fat: 8, fiber: 4.5 }, region: "middle_east", source: "global_cache" },
  { id: "tabbouleh", name: "Tabbouleh", aliases: ["tabouli"], servingG: 120, servingLabel: "1 cup", per100: { kcal: 72, protein: 2, carbs: 9, fat: 3.5, fiber: 2.6 }, region: "middle_east", source: "global_cache" },
  { id: "fattoush", name: "Fattoush", aliases: [], servingG: 160, servingLabel: "1 bowl", per100: { kcal: 78, protein: 2, carbs: 10, fat: 3.5, fiber: 2.2 }, region: "middle_east", source: "global_cache" },
  { id: "pita", name: "Pita bread", aliases: ["pitta"], servingG: 60, servingLabel: "1 pocket", per100: { kcal: 275, protein: 9, carbs: 55, fat: 1.2, fiber: 2.2 }, region: "middle_east", source: "global_cache" },
  { id: "labneh", name: "Labneh", aliases: [], servingG: 50, servingLabel: "2 tbsp", per100: { kcal: 146, protein: 7, carbs: 4, fat: 11, fiber: 0 }, region: "middle_east", source: "global_cache" },
  { id: "dates", name: "Dates, Medjool", aliases: ["date"], servingG: 48, servingLabel: "2 dates", per100: { kcal: 277, protein: 1.8, carbs: 75, fat: 0.2, fiber: 6.7 }, region: "middle_east", source: "global_cache" },
  { id: "turkish-coffee", name: "Turkish coffee", aliases: ["qahwa"], servingG: 60, servingLabel: "1 cup", per100: { kcal: 8, protein: 0.3, carbs: 1.2, fat: 0.1, fiber: 0 }, region: "middle_east", source: "global_cache" },
  { id: "ayran", name: "Ayran", aliases: ["doogh"], servingG: 200, servingLabel: "1 glass", per100: { kcal: 36, protein: 2.2, carbs: 3, fat: 1.6, fiber: 0 }, region: "middle_east", source: "global_cache" },
  { id: "manakeesh", name: "Manakeesh za'atar", aliases: ["manakish", "zaatar pie"], servingG: 120, servingLabel: "1", per100: { kcal: 268, protein: 7, carbs: 36, fat: 11, fiber: 2.8 }, region: "middle_east", source: "global_cache" },

  // ── Oceania ──────────────────────────────────────────────────────────────
  { id: "meat-pie", name: "Meat pie", aliases: ["aussie pie"], servingG: 170, servingLabel: "1 pie", per100: { kcal: 258, protein: 9, carbs: 22, fat: 15, fiber: 1.2 }, region: "oceania", source: "global_cache" },
  { id: "sausage-roll", name: "Sausage roll", aliases: [], servingG: 130, servingLabel: "1", per100: { kcal: 312, protein: 10, carbs: 22, fat: 20, fiber: 1 }, region: "oceania", source: "global_cache" },
  { id: "vegemite-toast", name: "Vegemite on toast", aliases: ["vegemite", "marmite"], servingG: 40, servingLabel: "1 slice", per100: { kcal: 228, protein: 10, carbs: 38, fat: 3.5, fiber: 3 }, region: "oceania", source: "global_cache" },
  { id: "flat-white", name: "Flat white", aliases: [], servingG: 160, servingLabel: "1 cup", per100: { kcal: 46, protein: 2.4, carbs: 3.6, fat: 2.4, fiber: 0 }, region: "oceania", source: "global_cache" },
  { id: "pavlova", name: "Pavlova with fruit", aliases: ["pav"], servingG: 100, servingLabel: "1 slice", per100: { kcal: 242, protein: 3, carbs: 48, fat: 5, fiber: 0.8 }, region: "oceania", source: "global_cache" },
  { id: "lamington", name: "Lamington", aliases: [], servingG: 55, servingLabel: "1 square", per100: { kcal: 365, protein: 4, carbs: 52, fat: 16, fiber: 1.6 }, region: "oceania", source: "global_cache" },

  // ── Drinks (cross-regional) ──────────────────────────────────────────────
  { id: "soy-milk", name: "Soy milk, unsweetened", aliases: ["soymilk"], servingG: 240, servingLabel: "1 cup", per100: { kcal: 33, protein: 2.9, carbs: 1.8, fat: 1.6, fiber: 0.4 }, region: "global", source: "global_cache" },
  { id: "hot-chocolate", name: "Hot chocolate", aliases: ["cocoa", "hot cocoa"], servingG: 240, servingLabel: "1 cup", per100: { kcal: 77, protein: 3.5, carbs: 11, fat: 2.3, fiber: 0.8 }, region: "global", source: "global_cache" },
  { id: "americano", name: "Americano", aliases: ["long black"], servingG: 240, servingLabel: "1 cup", per100: { kcal: 3, protein: 0.2, carbs: 0.4, fat: 0, fiber: 0 }, region: "global", source: "global_cache" },
  { id: "kefir", name: "Kefir, plain", aliases: [], servingG: 240, servingLabel: "1 cup", per100: { kcal: 43, protein: 3.3, carbs: 4.5, fat: 1, fiber: 0 }, region: "global", source: "global_cache" },
  { id: "coconut-milk-drink", name: "Coconut milk beverage", aliases: ["coconut milk"], servingG: 240, servingLabel: "1 cup", per100: { kcal: 31, protein: 0.2, carbs: 2.9, fat: 2.1, fiber: 0 }, region: "global", source: "global_cache" },
];
