/** ISO 3166-1 alpha-2 → continent name */
const COUNTRY_CONTINENT: Record<string, string> = {
  US: "North America",
  CA: "North America",
  MX: "North America",
  GT: "North America",
  CU: "North America",
  HT: "North America",
  DO: "North America",
  JM: "North America",
  CR: "North America",
  PA: "North America",
  BR: "South America",
  AR: "South America",
  CL: "South America",
  CO: "South America",
  PE: "South America",
  VE: "South America",
  EC: "South America",
  GB: "Europe",
  DE: "Europe",
  FR: "Europe",
  IT: "Europe",
  ES: "Europe",
  NL: "Europe",
  BE: "Europe",
  CH: "Europe",
  AT: "Europe",
  SE: "Europe",
  NO: "Europe",
  DK: "Europe",
  FI: "Europe",
  IE: "Europe",
  PT: "Europe",
  PL: "Europe",
  CZ: "Europe",
  RO: "Europe",
  GR: "Europe",
  UA: "Europe",
  RU: "Europe",
  TR: "Europe",
  CN: "Asia",
  JP: "Asia",
  KR: "Asia",
  IN: "Asia",
  ID: "Asia",
  PH: "Asia",
  VN: "Asia",
  TH: "Asia",
  MY: "Asia",
  SG: "Asia",
  HK: "Asia",
  TW: "Asia",
  PK: "Asia",
  BD: "Asia",
  SA: "Asia",
  AE: "Asia",
  IL: "Asia",
  IQ: "Asia",
  IR: "Asia",
  AU: "Oceania",
  NZ: "Oceania",
  FJ: "Oceania",
  EG: "Africa",
  NG: "Africa",
  ZA: "Africa",
  KE: "Africa",
  MA: "Africa",
  GH: "Africa",
  ET: "Africa",
  DZ: "Africa",
  TN: "Africa",
};

/** Approximate centroids when IP geo has country only */
export const COUNTRY_CENTROIDS: Record<string, { lat: number; lng: number; name: string }> = {
  US: { lat: 39.8283, lng: -98.5795, name: "United States" },
  CA: { lat: 56.1304, lng: -106.3468, name: "Canada" },
  GB: { lat: 55.3781, lng: -3.436, name: "United Kingdom" },
  DE: { lat: 51.1657, lng: 10.4515, name: "Germany" },
  FR: { lat: 46.2276, lng: 2.2137, name: "France" },
  AU: { lat: -25.2744, lng: 133.7751, name: "Australia" },
  IN: { lat: 20.5937, lng: 78.9629, name: "India" },
  BR: { lat: -14.235, lng: -51.9253, name: "Brazil" },
  MX: { lat: 23.6345, lng: -102.5528, name: "Mexico" },
  JP: { lat: 36.2048, lng: 138.2529, name: "Japan" },
  CN: { lat: 35.8617, lng: 104.1954, name: "China" },
  SG: { lat: 1.3521, lng: 103.8198, name: "Singapore" },
  AE: { lat: 23.4241, lng: 53.8478, name: "UAE" },
  NG: { lat: 9.082, lng: 8.6753, name: "Nigeria" },
  ZA: { lat: -30.5595, lng: 22.9375, name: "South Africa" },
  EG: { lat: 26.8206, lng: 30.8025, name: "Egypt" },
  IT: { lat: 41.8719, lng: 12.5674, name: "Italy" },
  ES: { lat: 40.4637, lng: -3.7492, name: "Spain" },
  NL: { lat: 52.1326, lng: 5.2913, name: "Netherlands" },
  SE: { lat: 60.1282, lng: 18.6435, name: "Sweden" },
  PH: { lat: 12.8797, lng: 121.774, name: "Philippines" },
  PK: { lat: 30.3753, lng: 69.3451, name: "Pakistan" },
  KR: { lat: 35.9078, lng: 127.7669, name: "South Korea" },
};

export function countryToContinent(countryCode: string | null | undefined): string | null {
  if (!countryCode) return null;
  return COUNTRY_CONTINENT[countryCode.toUpperCase()] ?? "Other";
}

export function countryDisplayName(code: string): string {
  return COUNTRY_CENTROIDS[code.toUpperCase()]?.name ?? code.toUpperCase();
}
